<?php

require_once './database.php';
$db = Database::getDatabase(true);
$rs = $db->query("USE accoun40_accounta_scheduler_tax");
$limit = $_POST['limit'];
$offset = $_POST['offset'];
$period = $_POST['period'];
if($period == 'month') {
$query1 = "SELECT ea_appointments.id id, delivery, start_datetime, end_datetime, TIMEDIFF(end_datetime, start_datetime) AS duration, MOD(HOUR(TIMEDIFF(end_datetime, start_datetime)), 24) hours, MINUTE(TIMEDIFF(end_datetime, start_datetime)) minutes, first_name, LEFT(last_name, 1) last_name, email, phone_number, address, suburb, city, id_users_customer, ea_services.name service_name, attendants_number, rental_property, rank, station_locale, years_in_job, is_done, estimate, hecs, (select count(ea_appointments.id) from ea_appointments LEFT JOIN ea_users ON ea_appointments.id_users_customer = ea_users.id LEFT JOIN ea_services ON ea_appointments.id_services = ea_services.id WHERE id_users_customer IS NOT NULL AND YEAR(start_datetime) = YEAR(CURDATE()) AND MONTH(start_datetime) = MONTH(CURDATE())) as full_count FROM ea_appointments LEFT JOIN ea_users ON ea_appointments.id_users_customer = ea_users.id LEFT JOIN ea_services ON ea_appointments.id_services = ea_services.id WHERE id_users_customer IS NOT NULL AND YEAR(start_datetime) = YEAR(CURDATE()) AND MONTH(start_datetime) = MONTH(CURDATE()) ORDER BY start_datetime DESC LIMIT ".$limit." OFFSET ".$offset;
$query2 = "SELECT ea_appointments.id id, delivery, start_datetime, end_datetime, TIMEDIFF(end_datetime, start_datetime) AS duration, MOD(HOUR(TIMEDIFF(end_datetime, start_datetime)), 24) hours, MINUTE(TIMEDIFF(end_datetime, start_datetime)) minutes, first_name, last_name, email, phone_number, address, suburb, city, id_users_customer, ea_services.name service_name, attendants_number, rental_property, rank, station_locale, years_in_job, is_done, estimate, hecs, (select count(ea_appointments.id) from ea_appointments LEFT JOIN ea_users ON ea_appointments.id_users_customer = ea_users.id LEFT JOIN ea_services ON ea_appointments.id_services = ea_services.id WHERE id_users_customer IS NOT NULL AND YEAR(start_datetime) = YEAR(CURDATE()) AND MONTH(start_datetime) = MONTH(CURDATE())) as full_count FROM ea_appointments LEFT JOIN ea_users ON ea_appointments.id_users_customer = ea_users.id LEFT JOIN ea_services ON ea_appointments.id_services = ea_services.id WHERE id_users_customer IS NOT NULL AND YEAR(start_datetime) = YEAR(CURDATE()) AND MONTH(start_datetime) = MONTH(CURDATE()) ORDER BY start_datetime DESC LIMIT ".$limit." OFFSET ".$offset; }
else if($period == 'week') {
$query1 = "SELECT ea_appointments.id id, delivery, start_datetime, end_datetime, TIMEDIFF(end_datetime, start_datetime) AS duration, MOD(HOUR(TIMEDIFF(end_datetime, start_datetime)), 24) hours, MINUTE(TIMEDIFF(end_datetime, start_datetime)) minutes, first_name, LEFT(last_name, 1) last_name, email, phone_number, address, suburb, city, id_users_customer, ea_services.name service_name, attendants_number, rental_property, rank, station_locale, years_in_job, is_done, estimate, hecs, (select count(ea_appointments.id) from ea_appointments LEFT JOIN ea_users ON ea_appointments.id_users_customer = ea_users.id LEFT JOIN ea_services ON ea_appointments.id_services = ea_services.id WHERE id_users_customer IS NOT NULL AND YEAR(start_datetime) = YEAR(CURDATE()) AND IF(DAYOFWEEK(CURDATE()) = 1, WEEK(start_datetime) = WEEK(CURDATE()) - 1, WEEK(start_datetime) = WEEK(CURDATE()))) as full_count FROM ea_appointments LEFT JOIN ea_users ON ea_appointments.id_users_customer = ea_users.id LEFT JOIN ea_services ON ea_appointments.id_services = ea_services.id WHERE id_users_customer IS NOT NULL AND YEAR(start_datetime) = YEAR(CURDATE()) AND IF(DAYOFWEEK(CURDATE()) = 1, WEEK(start_datetime) = WEEK(CURDATE()) - 1, WEEK(start_datetime) = WEEK(CURDATE())) ORDER BY start_datetime DESC LIMIT ".$limit." OFFSET ".$offset;
$query2 = "SELECT ea_appointments.id id, delivery, start_datetime, end_datetime, TIMEDIFF(end_datetime, start_datetime) AS duration, MOD(HOUR(TIMEDIFF(end_datetime, start_datetime)), 24) hours, MINUTE(TIMEDIFF(end_datetime, start_datetime)) minutes, first_name, last_name, email, phone_number, address, suburb, city, id_users_customer, ea_services.name service_name, attendants_number, rental_property, rank, station_locale, years_in_job, is_done, estimate, hecs, (select count(ea_appointments.id) from ea_appointments LEFT JOIN ea_users ON ea_appointments.id_users_customer = ea_users.id LEFT JOIN ea_services ON ea_appointments.id_services = ea_services.id WHERE id_users_customer IS NOT NULL AND YEAR(start_datetime) = YEAR(CURDATE()) AND IF(DAYOFWEEK(CURDATE()) = 1, WEEK(start_datetime) = WEEK(CURDATE()) - 1, WEEK(start_datetime) = WEEK(CURDATE()))) as full_count FROM ea_appointments LEFT JOIN ea_users ON ea_appointments.id_users_customer = ea_users.id LEFT JOIN ea_services ON ea_appointments.id_services = ea_services.id WHERE id_users_customer IS NOT NULL AND YEAR(start_datetime) = YEAR(CURDATE()) AND IF(DAYOFWEEK(CURDATE()) = 1, WEEK(start_datetime) = WEEK(CURDATE()) - 1, WEEK(start_datetime) = WEEK(CURDATE())) ORDER BY start_datetime DESC LIMIT ".$limit." OFFSET ".$offset; }
else if($period == 'today') {
$query1 = "SELECT ea_appointments.id id, delivery, start_datetime, end_datetime, TIMEDIFF(end_datetime, start_datetime) AS duration, MOD(HOUR(TIMEDIFF(end_datetime, start_datetime)), 24) hours, MINUTE(TIMEDIFF(end_datetime, start_datetime)) minutes, first_name, LEFT(last_name, 1) last_name, email, phone_number, address, suburb, city, id_users_customer, ea_services.name service_name, attendants_number, rental_property, rank, station_locale, years_in_job, is_done, estimate, hecs, (select count(ea_appointments.id) from ea_appointments LEFT JOIN ea_users ON ea_appointments.id_users_customer = ea_users.id LEFT JOIN ea_services ON ea_appointments.id_services = ea_services.id WHERE id_users_customer IS NOT NULL AND is_done = 0 AND DATE(start_datetime) = DATE(CURDATE())) as full_count FROM ea_appointments LEFT JOIN ea_users ON ea_appointments.id_users_customer = ea_users.id LEFT JOIN ea_services ON ea_appointments.id_services = ea_services.id WHERE id_users_customer IS NOT NULL AND is_done = 0 AND DATE(start_datetime) = DATE(CURDATE()) ORDER BY start_datetime LIMIT ".$limit." OFFSET ".$offset;
$query2 = "SELECT ea_appointments.id id, delivery, start_datetime, end_datetime, TIMEDIFF(end_datetime, start_datetime) AS duration, MOD(HOUR(TIMEDIFF(end_datetime, start_datetime)), 24) hours, MINUTE(TIMEDIFF(end_datetime, start_datetime)) minutes, first_name, last_name, email, phone_number, address, suburb, city, id_users_customer, ea_services.name service_name, attendants_number, rental_property, rank, station_locale, years_in_job, is_done, estimate, hecs, (select count(ea_appointments.id) from ea_appointments LEFT JOIN ea_users ON ea_appointments.id_users_customer = ea_users.id LEFT JOIN ea_services ON ea_appointments.id_services = ea_services.id WHERE id_users_customer IS NOT NULL AND is_done = 0 AND DATE(start_datetime) = DATE(CURDATE())) as full_count FROM ea_appointments LEFT JOIN ea_users ON ea_appointments.id_users_customer = ea_users.id LEFT JOIN ea_services ON ea_appointments.id_services = ea_services.id WHERE id_users_customer IS NOT NULL AND is_done = 0 AND DATE(start_datetime) = DATE(CURDATE()) ORDER BY start_datetime LIMIT ".$limit." OFFSET ".$offset; }
else if($period == 'tomorrow') {
$query1 = "SELECT ea_appointments.id id, delivery, start_datetime, end_datetime, TIMEDIFF(end_datetime, start_datetime) AS duration, MOD(HOUR(TIMEDIFF(end_datetime, start_datetime)), 24) hours, MINUTE(TIMEDIFF(end_datetime, start_datetime)) minutes, first_name, LEFT(last_name, 1) last_name, email, phone_number, address, suburb, city, id_users_customer, ea_services.name service_name, attendants_number, rental_property, rank, station_locale, years_in_job, is_done, estimate, hecs, (select count(ea_appointments.id) from ea_appointments LEFT JOIN ea_users ON ea_appointments.id_users_customer = ea_users.id LEFT JOIN ea_services ON ea_appointments.id_services = ea_services.id WHERE id_users_customer IS NOT NULL AND is_done = 0 AND DATE(start_datetime) = DATE_ADD(CURDATE(), INTERVAL 1 DAY)) as full_count FROM ea_appointments LEFT JOIN ea_users ON ea_appointments.id_users_customer = ea_users.id LEFT JOIN ea_services ON ea_appointments.id_services = ea_services.id WHERE id_users_customer IS NOT NULL AND is_done = 0 AND DATE(start_datetime) = DATE_ADD(CURDATE(), INTERVAL 1 DAY) ORDER BY start_datetime LIMIT ".$limit." OFFSET ".$offset;
$query2 = "SELECT ea_appointments.id id, delivery, start_datetime, end_datetime, TIMEDIFF(end_datetime, start_datetime) AS duration, MOD(HOUR(TIMEDIFF(end_datetime, start_datetime)), 24) hours, MINUTE(TIMEDIFF(end_datetime, start_datetime)) minutes, first_name, last_name, email, phone_number, address, suburb, city, id_users_customer, ea_services.name service_name, attendants_number, rental_property, rank, station_locale, years_in_job, is_done, estimate, hecs, (select count(ea_appointments.id) from ea_appointments LEFT JOIN ea_users ON ea_appointments.id_users_customer = ea_users.id LEFT JOIN ea_services ON ea_appointments.id_services = ea_services.id WHERE id_users_customer IS NOT NULL AND is_done = 0 AND DATE(start_datetime) = DATE_ADD(CURDATE(), INTERVAL 1 DAY)) as full_count FROM ea_appointments LEFT JOIN ea_users ON ea_appointments.id_users_customer = ea_users.id LEFT JOIN ea_services ON ea_appointments.id_services = ea_services.id WHERE id_users_customer IS NOT NULL AND is_done = 0 AND DATE(start_datetime) = DATE_ADD(CURDATE(), INTERVAL 1 DAY) ORDER BY start_datetime LIMIT ".$limit." OFFSET ".$offset; }
else if($period == 'new') {
$query1 = "SELECT ea_appointments.id id, delivery, book_datetime, start_datetime, end_datetime, TIMEDIFF(end_datetime, start_datetime) AS duration, MOD(HOUR(TIMEDIFF(end_datetime, start_datetime)), 24) hours, MINUTE(TIMEDIFF(end_datetime, start_datetime)) minutes, first_name, LEFT(last_name, 1) last_name, email, phone_number, address, suburb, city, ea_services.name service_name, attendants_number, is_done, estimate, hecs, rank, station_locale, years_in_job, promo, wre, pf, ea_appointments.bsb bsb, (select count(ea_appointments.id) from ea_appointments LEFT JOIN ea_users ON ea_appointments.id_users_customer = ea_users.id LEFT JOIN ea_services ON ea_appointments.id_services = ea_services.id WHERE id_users_customer IS NOT NULL AND (promo = 0 OR wre = 0 OR pf = 0 OR ea_appointments.bsb = 0) AND start_datetime >= CURRENT_TIMESTAMP()) as full_count FROM ea_appointments LEFT JOIN ea_users ON ea_appointments.id_users_customer = ea_users.id LEFT JOIN ea_services ON ea_appointments.id_services = ea_services.id WHERE id_users_customer IS NOT NULL AND (promo = 0 OR wre = 0 OR pf = 0 OR ea_appointments.bsb = 0) AND start_datetime >= CURRENT_TIMESTAMP() ORDER BY start_datetime LIMIT ".$limit." OFFSET ".$offset;
$query2 = "SELECT ea_appointments.id id, delivery, book_datetime, start_datetime, end_datetime, TIMEDIFF(end_datetime, start_datetime) AS duration, MOD(HOUR(TIMEDIFF(end_datetime, start_datetime)), 24) hours, MINUTE(TIMEDIFF(end_datetime, start_datetime)) minutes, first_name, last_name, email, phone_number, address, suburb, city, ea_services.name service_name, attendants_number, is_done, estimate, hecs, rank, station_locale, years_in_job, promo, wre, pf, ea_appointments.bsb bsb, (select count(ea_appointments.id) from ea_appointments LEFT JOIN ea_users ON ea_appointments.id_users_customer = ea_users.id LEFT JOIN ea_services ON ea_appointments.id_services = ea_services.id WHERE id_users_customer IS NOT NULL AND (promo = 0 OR wre = 0 OR pf = 0 OR ea_appointments.bsb = 0) AND start_datetime >= CURRENT_TIMESTAMP()) as full_count FROM ea_appointments LEFT JOIN ea_users ON ea_appointments.id_users_customer = ea_users.id LEFT JOIN ea_services ON ea_appointments.id_services = ea_services.id WHERE id_users_customer IS NOT NULL AND (promo = 0 OR wre = 0 OR pf = 0 OR ea_appointments.bsb = 0) AND start_datetime >= CURRENT_TIMESTAMP() ORDER BY start_datetime LIMIT ".$limit." OFFSET ".$offset; }
$rs = $db->query($query2);
$valid = true;
if(!is_bool($rs)) {
    $arr = array();
    while($obj = $rs->fetch_object()) {
    	array_push($arr, $obj);
    }
	$json = json_encode($arr);
	if(strlen($json) > 0) echo $json;
	else $valid = false;
} else $valid = false;
if($valid == false) {
    $rs = $db->query($query1);
    if(!is_bool($rs)) {
        $arr = array();
        while($obj = $rs->fetch_object()) {
        	array_push($arr, $obj);
        }
    	$json = json_encode($arr);
    	if(strlen($json) > 0) echo $json;
    	else echo $query1;
    } else echo $query1;
}
?>